### ISSUE TITLE
Searching for "Don" results in a 500 Server Error

### ISSUE THREAD

**Issue by oskarlh** [LogicAndTrick/twhl#21]
https://twhl.info/search/index?search=Don or https://twhl.info/search/index?search=don or https://twhl.info/search/index?search=don+abcdef or https://twhl.info/search/index?search=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa+don

**Comment by oskarlh** [comment]
I'm really curious what's causing this

**Comment by LogicAndTrick** [comment]
Fixed, thanks! It was caused by posts from deleted threads being matched in the search results. The thread doesn't exist when trying to display search results, causing a null pointer exception.
