### ISSUE TITLE
Bad links when viewing a revision of a wiki page from before it was renamed 

### ISSUE THREAD

**Issue by oskarlh** [LogicAndTrick/twhl#26]
The wiki page "AAATRIGGER texture" was renamed "AAATRIGGER".
https://twhl.info/wiki/page/AAATRIGGER : the Edit and History links work as expected.
But go to the history page and click on Windawz's "#5725". It takes you to https://twhl.info/wiki/page/AAATRIGGER_texture/5725 . On that page, clicking the History link gives you 404, the Edit link gives you 500, and the "AAATRIGGER texture" link left of the Edit link takes you to a page that tells you the article doesn't exist.

**Comment by LogicAndTrick** [comment]
It took me a while, but I've fixed this one now! Thanks for the bug report.
