### ISSUE TITLE
/api error

### ISSUE THREAD

**Issue by oskarlh** [LogicAndTrick/twhl#35]
ApiController.php:584 `foreach ($obj->visible as $prop) {`
fails because of image-upload's
ApiController.php:519 `'object' => \stdClass::class,`
stdClass doesn't have the visible property.

This is why https://twhl.info/api gives 500

Solutions: change the object type or only iterate $obj->visible if isset($obj->visible)

**Comment by LogicAndTrick** [comment]
Fixed, thanks!
