### ISSUE TITLE
[Wiki] Preview comments is not working

### ISSUE THREAD

**Issue by JoelTroch** [LogicAndTrick/twhl#4]
Using the latest version of Opera on Windows, previewing wiki comment doesn't work due to missing stuff in JQuery, console output :

```
POST http://beta2.twhl.info/api/format?field=text 404 (Not Found)
send @ jquery.js:8630
ajax @ jquery.js:8166
J.(anonymous function) @ jquery.js:8311
(anonymous function) @ Home:162
dispatch @ jquery.js:4435
m.handle @ jquery.js:4121
```

How to reproduce : go to any wiki page, type anything or nothing in the comment textarea, press the "Update Preview" button.

**Comment by LogicAndTrick** [comment]
Is this specific to Opera or do other browsers trigger it? I though Opera was just a skinned Chrome so I haven't tested on it.

Does it also happen on [twhl-beta.info](http://twhl-beta.info)? I should update the docs, beta2.twhl.info is out of date.

**Comment by JoelTroch** [comment]
beta2.twhl.info : Problem also appear on IE 11 and Microsoft Edge.

twhl-beta.info : Works on all browsers.

Opera, Chromium and Google Chrome are using the Blink layout engine mainly developed by Chromium developers with contributions from Google, Opera Software ASA, Intel, Samsung. So the only differences between Opera, Chromium and Google Chrome are the GUI, extensions, features, how updates are managed, etc...

**Comment by LogicAndTrick** [comment]
Thanks for testing. Closing because the updated beta site works.
