### ISSUE TITLE
[WikiCode] Styling isn't applied when a sentence ends with a colon

### ISSUE THREAD

**Issue by JoelTroch** [LogicAndTrick/twhl#41]
When writing a wiki article, I have the following sentence:

```
Same thing with `Schedule_t` for a *schedule*:
```

In the preview window, the word "schedule" isn't in bold and the asterisks are shown (`Schedule_t` is fine and shown as inlined code). My guess is that the parser think I'm trying to write a smiley/emoticon/emoji.

**Comment by LogicAndTrick** [comment]
Finally fixed this one. My parser isn't very good so I have to be kinda careful about which symbols are allowed...
