### ISSUE TITLE
Add OpenSearch provider

### ISSUE THREAD

**Issue by LogicAndTrick** [LogicAndTrick/twhl#49]
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by oskarlh** [comment]
Just the OpenSearch Description, or an Atom or RSS feed for the results too? If it's the former, I could take a crack at it

**Comment by LogicAndTrick** [comment]
Just the thing that prompts browsers to add the site as a search provider. I don't think that needs a feed for results, it should just open the search page.

So it shows up in these settings and if I set up a "twhl" keyword and type "twhl something" in my search bar it takes me to https://twhl.info/search/index?search=something

![image](https://user-images.githubusercontent.com/3071180/210160184-090c1c45-95a0-486b-a0b9-f5ec178ee17e.png)
