### ISSUE TITLE
Old forum threads fail to load

### ISSUE THREAD

**Issue by oskarlh** [LogicAndTrick/twhl#63]
Check out the last pages in the thread lists. If you try to view these threads (which somehow have -1 replies) you get a 500 server error:
https://twhl.info/forum/view/goldsource?page=162
And page 163 and 164 are empty

**Comment by oskarlh** [comment]
@LogicAndTrick Looks like the fix didn't work https://twhl.info/thread/view/6282

**Comment by LogicAndTrick** [comment]
Ahh yep. It's working when logged out but I didn't test with normal access.

**Comment by LogicAndTrick** [comment]
Hopefully fixed properly this time!
