### ISSUE TITLE
[vault:] tags show the wrong date

### ISSUE THREAD

**Issue by oskarlh** [LogicAndTrick/twhl#70]
As seen here https://twhl.info/wiki/page/TWHL_Community_Collaborations
![image](https://user-images.githubusercontent.com/11921030/178590668-90e393d4-d348-4ccb-8345-5af71b94fb3f.png)
It's showing the date of the last update instead of the date the map was first posted.

**Comment by LogicAndTrick** [comment]
Thanks for the bug reports, fixed a bunch of them!

**Comment by oskarlh** [comment]
Five in one day, nice!
