### ISSUE TITLE
Wiki - Detect web browser tab/window closing to add a warning when creating/editing articles

### ISSUE THREAD

**Issue by JoelTroch** [LogicAndTrick/twhl#74]
Right now, if you create or edit a wiki article and close your web browser's tab or window, the unsaved changes are lost.

It would be nice to add detection of web browser's closing tab/window event to add a warning like this:

_"You made changes but did not saved them. Are you sure you want to close your web browser's tab or window? Unsaved changes are lost."_

**Comment by LogicAndTrick** [comment]
Fixed now. Most browsers override the alert message, so it'll just be a generic one.
