### ISSUE TITLE
WikiCode - Internal links does not support anchors

### ISSUE THREAD

**Issue by JoelTroch** [LogicAndTrick/twhl#75]
**How to reproduce?**

1. Edit this [wiki article](https://twhl.info/wiki/page/Entity_Programming_-_Introduction_to_Entities_with_Animated_Models).
2. Replace this "external -> internal link" warning from: `[url=https://twhl.info/wiki/page/Monsters_Programming_-_The_Concepts_of_Half-Life%27s_AI#h6186a030dcc80]activity[/url]` to `[[Monsters Programming - The Concepts of Half-Life's AI#h6186a030dcc80|activity]]`

**Expected**

I should be redirected on that wiki [article and section](https://twhl.info/wiki/page/Monsters_Programming_-_The_Concepts_of_Half-Life%27s_AI#h632ae8343c677).

**Actual**

"Page not found: Monsters_Programming_-_The_Concepts_of_Half-Life's_AIh6186a030dcc80"

**Comment by LogicAndTrick** [comment]
Fixed, I also updated the randomly generated anchors since it's impossible to permalink if the anchor changes every time you edit.
