### ISSUE TITLE
Message probably intended for forum moderators is shown to others

### ISSUE THREAD

**Issue by oskarlh** [LogicAndTrick/twhl#80]
The "Careful!" text:
![Screenshot_20221216-175359](https://user-images.githubusercontent.com/11921030/208149469-a719ebe3-4feb-4e1c-a4ab-65775889358e.png)

https://twhl.info/thread/view/20328
The thread is 4 months old and I can still post in it. I am of course not a forum moderator, but that message would only make sense if I had some special permission to post.

I guess the 90 here
https://github.com/LogicAndTrick/twhl/blob/a4688f56ef27f827161804542344ece09727caae/resources/views/forums/thread/view.blade.php#L104
should instead be ForumThread::THREAD_LOCK_DAYS

**Comment by LogicAndTrick** [comment]
Thanks :)
