### ISSUE TITLE
Errors in the OpenAPI spec

### ISSUE THREAD

**Issue by oskarlh** [LogicAndTrick/twhl#81]
https://twhl.info/api is missing
```
#/definitions/Motm
#/definitions/VaultItemReview
#/definitions/WikiRevisionBook
#/definitions/WikiRevisionCredit
```

There are also other errors according to https://apitools.dev/swagger-parser/online/ such as `"type": "int"` being used instead of `"type": "integer"`

**Comment by LogicAndTrick** [comment]
Fixed in 04e0a311cdb383a945d34bb0e779f7c2e277849f
